### PR TITLE
Sitemap + migrating gatsby v2 to v3 + refactored components

### LINKED ISSUE #7: Sitemap.xml

### PR DESCRIPTION
**Pull request by ceboola**
feat: added sitemap, refactored CommonIcon component and couple of ex…
…ports in other components, prettified, added new way of generating svg sprite, separated icons to new files, migrated from gatsby v2 to v3

Closes #7

### CODE REVIEW

**Comment by BranDougherty** [comment]
@acdvs @Appnautic Are either of you willing to take a look at this in the near future? I understand it's been less than a week since this was opened, but given the lack of recent activity on this project I'd like to check that this will get reviewed in a timely fashion (it's not often we get people willing to work on these projects, they deserve some reassurance that their efforts won't be ignored). I'd like to know your decisions so I can try and get someone else on this if needed.

**Comment by acdvs** [comment]
I can review it in the next day or two.

**Comment by BranDougherty** [comment]
Great, thank you.

**Comment by ceboola** [comment]
cool, don't worry most of the changes I'm pretty sure are code formatting (surprisingly no one has done this before me lol :P)

**Review by acdvs — APPROVED** [review]
Changes look good. Thanks for standardizing everything!

**Pull request merged**
